server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /sw.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /manifest.json {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
